### PR TITLE
Added a thread id output.

### PR DESCRIPTION
**Pull request by kurtlawrence**
Added a thread id output such that the output follows `<time> <level> <thread_id>`.

Thread id comes from [`std::thread::current().id()`](https://doc.rust-lang.org/std/thread/struct.ThreadId.html) as a `ThreadId` which, for now, is backed by a `u64`.

I decided to output the id as a number, encased in brackets. I am not too fussed about the format. `ThreadId` does not implement `Display` so I have deconstructed the debug format to return just the number (debug output is `ThreadId(#)`).

I decided to use the string replace function rather than take a slice `&id[9..id.len()-1]` as there may be no guarantee that the debug format remains constant.

😄

### CODE REVIEW

**Comment by Drakulix** [comment]
Thanks, looks good, just some minor complains.

1. Can you remove the .vscode files please?
2. Can you format the code using rustfmt?

**Comment by kurtlawrence** [comment]
Hi @Drakulix,

I removed the `.vscode` folder, sorry that slipped in there.

Regarding the formatting using `rustfmt`, I used the default formatting settings and it has changed more than just my code (mostly splitting `where` lines). Did you have any specific formatting settings?


Cheers,

Kurt

**Comment by Drakulix** [comment]
I thought, I have a rustfmt config in place, turns out I have not, I just noticed some weird intends in your code.

Thanks for your work, I will take care of the formatting and merge this soon.

**Comment by Drakulix** [comment]
Merged manually via #37

**Pull request closed without merging**
